-- Community + Admin tooling tables
-- Run this in the Supabase SQL editor.

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_by text not null references public.users(uid) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_uid text not null references public.users(uid) on delete cascade,
  joined_at timestamptz not null default now(),
  unique (team_id, user_uid)
);

create table if not exists public.team_challenges (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  title text not null,
  description text,
  due_date date,
  created_by text not null references public.users(uid) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.team_challenge_submissions (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null references public.team_challenges(id) on delete cascade,
  user_uid text not null references public.users(uid) on delete cascade,
  note text not null,
  submitted_at timestamptz not null default now(),
  unique (challenge_id, user_uid)
);

create index if not exists idx_team_members_team_id on public.team_members(team_id);
create index if not exists idx_team_members_user_uid on public.team_members(user_uid);
create index if not exists idx_team_challenges_team_id on public.team_challenges(team_id);
create index if not exists idx_team_challenge_submissions_challenge_id on public.team_challenge_submissions(challenge_id);
create index if not exists idx_team_challenge_submissions_user_uid on public.team_challenge_submissions(user_uid);

alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.team_challenges enable row level security;
alter table public.team_challenge_submissions enable row level security;

-- Teams policies
create policy "Teams can be viewed by authenticated users"
  on public.teams for select
  using (auth.role() = 'authenticated');

create policy "Team creator can create team"
  on public.teams for insert
  with check (auth.uid()::text = created_by);

create policy "Team creator can update team"
  on public.teams for update
  using (auth.uid()::text = created_by);

create policy "Team creator can delete team"
  on public.teams for delete
  using (auth.uid()::text = created_by);

-- Team members policies
create policy "Team members can be viewed by authenticated users"
  on public.team_members for select
  using (auth.role() = 'authenticated');

create policy "Users can join themselves"
  on public.team_members for insert
  with check (auth.uid()::text = user_uid);

create policy "Team members can add others"
  on public.team_members for insert
  with check (
    exists (
      select 1
      from public.team_members tm
      where tm.team_id = team_members.team_id
        and tm.user_uid = auth.uid()::text
    )
    or exists (
      select 1
      from public.teams t
      where t.id = team_members.team_id
        and t.created_by = auth.uid()::text
    )
  );

create policy "Users can leave themselves"
  on public.team_members for delete
  using (auth.uid()::text = user_uid);

-- Team challenges policies
create policy "Team challenges visible to authenticated users"
  on public.team_challenges for select
  using (auth.role() = 'authenticated');

create policy "Team challenge creator can create"
  on public.team_challenges for insert
  with check (auth.uid()::text = created_by);

create policy "Team challenge creator can update"
  on public.team_challenges for update
  using (auth.uid()::text = created_by);

create policy "Team challenge creator can delete"
  on public.team_challenges for delete
  using (auth.uid()::text = created_by);

-- Team challenge submissions policies
create policy "Team submissions visible to authenticated users"
  on public.team_challenge_submissions for select
  using (auth.role() = 'authenticated');

create policy "Users can submit for themselves"
  on public.team_challenge_submissions for insert
  with check (auth.uid()::text = user_uid);

create policy "Users can update their submission"
  on public.team_challenge_submissions for update
  using (auth.uid()::text = user_uid);

create policy "Users can delete their submission"
  on public.team_challenge_submissions for delete
  using (auth.uid()::text = user_uid);

-- Playground projects
create table if not exists public.playground_projects (
  id bigint generated by default as identity primary key,
  name text not null,
  language text not null,
  created_by text not null references public.users(uid) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.playground_project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.playground_projects(id) on delete cascade,
  user_uid text not null references public.users(uid) on delete cascade,
  added_by text not null references public.users(uid) on delete cascade,
  added_at timestamptz not null default now(),
  unique (project_id, user_uid)
);

create table if not exists public.playground_project_files (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.playground_projects(id) on delete cascade,
  path text not null,
  created_by text not null references public.users(uid) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, path)
);

create table if not exists public.playground_project_activity (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.playground_projects(id) on delete cascade,
  user_uid text not null references public.users(uid) on delete cascade,
  action text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists idx_playground_projects_team_id on public.playground_projects(team_id);
create index if not exists idx_playground_project_members_project_id on public.playground_project_members(project_id);
create index if not exists idx_playground_project_members_user_uid on public.playground_project_members(user_uid);
create index if not exists idx_playground_project_files_project_id on public.playground_project_files(project_id);
create index if not exists idx_playground_project_activity_project_id on public.playground_project_activity(project_id);

alter table public.playground_projects enable row level security;
alter table public.playground_project_members enable row level security;
alter table public.playground_project_files enable row level security;
alter table public.playground_project_activity enable row level security;

create policy "Playground projects visible to authenticated users"
  on public.playground_projects for select
  using (
    auth.role() = 'authenticated' and (
      auth.uid()::text = created_by
      or exists (
        select 1 from public.playground_project_members ppm
        where ppm.project_id = playground_projects.id
          and ppm.user_uid = auth.uid()::text
      )
      or (team_id is not null and exists (
        select 1 from public.team_members tm
        where tm.team_id = playground_projects.team_id
          and tm.user_uid = auth.uid()::text
      ))
      or exists (
        select 1 from public.users u
        where u.uid = auth.uid()::text
          and u.role = 'PATRON'
      )
    )
  );

create policy "Playground projects create"
  on public.playground_projects for insert
  with check (auth.uid()::text = created_by);

create policy "Playground projects update"
  on public.playground_projects for update
  using (
    auth.uid()::text = created_by
    or exists (
      select 1 from public.playground_project_members ppm
      where ppm.project_id = playground_projects.id
        and ppm.user_uid = auth.uid()::text
    )
    or (team_id is not null and exists (
      select 1 from public.team_members tm
      where tm.team_id = playground_projects.team_id
        and tm.user_uid = auth.uid()::text
    ))
    or exists (
      select 1 from public.users u
      where u.uid = auth.uid()::text
        and u.role = 'PATRON'
    )
  );

create policy "Playground projects delete"
  on public.playground_projects for delete
  using (
    auth.uid()::text = created_by
    or exists (
      select 1 from public.playground_project_members ppm
      where ppm.project_id = playground_projects.id
        and ppm.user_uid = auth.uid()::text
    )
    or (team_id is not null and exists (
      select 1 from public.team_members tm
      where tm.team_id = playground_projects.team_id
        and tm.user_uid = auth.uid()::text
    ))
    or exists (
      select 1 from public.users u
      where u.uid = auth.uid()::text
        and u.role = 'PATRON'
    )
  );

create policy "Project members visible"
  on public.playground_project_members for select
  using (auth.role() = 'authenticated');

create policy "Project members insert"
  on public.playground_project_members for insert
  with check (
    auth.role() = 'authenticated' and (
      exists (
        select 1 from public.playground_projects p
        where p.id = playground_project_members.project_id
          and (
            p.created_by = auth.uid()::text
            or (p.team_id is not null and exists (
              select 1 from public.team_members tm
              where tm.team_id = p.team_id
                and tm.user_uid = auth.uid()::text
            ))
            or exists (
              select 1 from public.playground_project_members ppm
              where ppm.project_id = p.id
                and ppm.user_uid = auth.uid()::text
            )
          )
      )
      or exists (
        select 1 from public.users u
        where u.uid = auth.uid()::text and u.role = 'PATRON'
      )
    )
  );

create policy "Project members delete"
  on public.playground_project_members for delete
  using (
    auth.role() = 'authenticated' and (
      user_uid = auth.uid()::text
      or exists (
        select 1 from public.playground_projects p
        where p.id = playground_project_members.project_id
          and p.created_by = auth.uid()::text
      )
      or exists (
        select 1 from public.users u
        where u.uid = auth.uid()::text and u.role = 'PATRON'
      )
    )
  );

create policy "Playground files select"
  on public.playground_project_files for select
  using (auth.role() = 'authenticated');

create policy "Playground files insert"
  on public.playground_project_files for insert
  with check (
    exists (
      select 1 from public.playground_projects p
      where p.id = playground_project_files.project_id
        and (
          p.created_by = auth.uid()::text
          or (p.team_id is not null and exists (
            select 1 from public.team_members tm
            where tm.team_id = p.team_id
              and tm.user_uid = auth.uid()::text
          ))
        )
    )
  );

create policy "Playground files update"
  on public.playground_project_files for update
  using (
    exists (
      select 1 from public.playground_projects p
      where p.id = playground_project_files.project_id
        and (
          p.created_by = auth.uid()::text
          or (p.team_id is not null and exists (
            select 1 from public.team_members tm
            where tm.team_id = p.team_id
              and tm.user_uid = auth.uid()::text
          ))
        )
    )
  );

create policy "Playground files delete"
  on public.playground_project_files for delete
  using (
    exists (
      select 1 from public.playground_projects p
      where p.id = playground_project_files.project_id
        and (
          p.created_by = auth.uid()::text
          or (p.team_id is not null and exists (
            select 1 from public.team_members tm
            where tm.team_id = p.team_id
              and tm.user_uid = auth.uid()::text
          ))
        )
    )
  );

create policy "Playground activity select"
  on public.playground_project_activity for select
  using (auth.role() = 'authenticated');

create policy "Playground activity insert"
  on public.playground_project_activity for insert
  with check (
    exists (
      select 1 from public.playground_projects p
      where p.id = playground_project_activity.project_id
        and (
          p.created_by = auth.uid()::text
          or (p.team_id is not null and exists (
            select 1 from public.team_members tm
            where tm.team_id = p.team_id
              and tm.user_uid = auth.uid()::text
          ))
        )
    )
  );

-- Storage bucket for playground project files
insert into storage.buckets (id, name, public)
values ('project_files', 'project_files', false)
on conflict (id) do nothing;

create policy "Project files read"
  on storage.objects for select
  using (bucket_id = 'project_files' and auth.role() = 'authenticated');

create policy "Project files write"
  on storage.objects for insert
  with check (bucket_id = 'project_files' and auth.role() = 'authenticated');

create policy "Project files update"
  on storage.objects for update
  using (bucket_id = 'project_files' and auth.role() = 'authenticated');

create policy "Project files delete"
  on storage.objects for delete
  using (bucket_id = 'project_files' and auth.role() = 'authenticated');
