


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."broadcast_public_messages_trigger"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  PERFORM realtime.broadcast_changes(
    'room:' || COALESCE(NEW.room_id, OLD.room_id)::text || ':messages',
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );
  RETURN COALESCE(NEW, OLD);
END;
$$;


ALTER FUNCTION "public"."broadcast_public_messages_trigger"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."current_user_id"() RETURNS "uuid"
    LANGUAGE "sql" STABLE
    AS $$
  SELECT (auth.uid())::uuid;
$$;


ALTER FUNCTION "public"."current_user_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."room_messages_broadcast_trigger"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  PERFORM realtime.broadcast_changes(
    'room:' || COALESCE(NEW.room_id, OLD.room_id)::text || ':messages',
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );
  RETURN COALESCE(NEW, OLD);
END;
$$;


ALTER FUNCTION "public"."room_messages_broadcast_trigger"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."user_uploads_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."user_uploads_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."activities" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "description" "text",
    "location" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "category" "text" DEFAULT 'OTHER'::"text"
);


ALTER TABLE "public"."activities" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."activities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."activities_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."activities_id_seq" OWNED BY "public"."activities"."id";



CREATE TABLE IF NOT EXISTS "public"."activity_rsvps" (
    "id" bigint NOT NULL,
    "activity_id" bigint,
    "user_uid" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."activity_rsvps" OWNER TO "postgres";


ALTER TABLE "public"."activity_rsvps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activity_rsvps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."attendance" (
    "id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "activity_id" bigint NOT NULL,
    "status" "text" NOT NULL,
    "recorded_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "attendance_status_check" CHECK (("status" = ANY (ARRAY['Present'::"text", 'Absent'::"text", 'Excused'::"text"])))
);


ALTER TABLE "public"."attendance" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."attendance_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."attendance_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."attendance_id_seq" OWNED BY "public"."attendance"."id";



CREATE TABLE IF NOT EXISTS "public"."challenge_submissions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "challenge_id" "uuid" NOT NULL,
    "user_uid" "text" NOT NULL,
    "content" "text" NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."challenge_submissions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."challenges" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "deadline" timestamp with time zone NOT NULL,
    "created_by" "text" NOT NULL,
    "status" "text" DEFAULT 'ACTIVE'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "difficulty" "text" DEFAULT 'BEGINNER'::"text"
);


ALTER TABLE "public"."challenges" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."feature_flags" (
    "id" integer DEFAULT 1 NOT NULL,
    "show_feed" boolean DEFAULT true NOT NULL,
    "show_activities" boolean DEFAULT true NOT NULL,
    "show_attendance" boolean DEFAULT true NOT NULL,
    "show_projects" boolean DEFAULT true NOT NULL,
    "show_resources" boolean DEFAULT true NOT NULL,
    "show_chat" boolean DEFAULT true NOT NULL,
    "show_showcase" boolean DEFAULT true NOT NULL,
    "show_suggestions" boolean DEFAULT true NOT NULL,
    "show_challenges" boolean DEFAULT true NOT NULL,
    "show_roadmap" boolean DEFAULT true NOT NULL,
    "show_community" boolean DEFAULT true NOT NULL,
    "show_playground" boolean DEFAULT true NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "show_voting" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."feature_flags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."feed_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "feed_item_id" bigint NOT NULL,
    "user_uid" "uuid" NOT NULL,
    "content" "text" NOT NULL
);


ALTER TABLE "public"."feed_comments" OWNER TO "postgres";


ALTER TABLE "public"."feed_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feed_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."feed_items" (
    "id" bigint NOT NULL,
    "type" "text" NOT NULL,
    "author_uid" "text" NOT NULL,
    "title" "text",
    "message" "text" NOT NULL,
    "likes" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'eat'::"text") NOT NULL,
    "image_url" "text",
    CONSTRAINT "feed_items_type_check" CHECK (("type" = ANY (ARRAY['EVENT_ANNOUNCEMENT'::"text", 'MEMBER_POST'::"text", 'NEWS_UPDATE'::"text", 'POLL'::"text"])))
);


ALTER TABLE "public"."feed_items" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."feed_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."feed_items_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."feed_items_id_seq" OWNED BY "public"."feed_items"."id";



CREATE TABLE IF NOT EXISTS "public"."game_leaderboard" (
    "id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "game_key" "text" NOT NULL,
    "best_value" integer NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."game_leaderboard" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."game_leaderboard_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."game_leaderboard_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."game_leaderboard_id_seq" OWNED BY "public"."game_leaderboard"."id";



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "room_id" "uuid" NOT NULL,
    "sender_id" "uuid" NOT NULL,
    "content" "text",
    "metadata" "jsonb" DEFAULT '{}'::"jsonb",
    "edited_at" timestamp with time zone,
    "deleted" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "recipient_uid" "uuid",
    "message" "text" NOT NULL,
    "is_read" boolean DEFAULT false NOT NULL,
    "link_to" "text",
    "user_uid" "text"
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


COMMENT ON TABLE "public"."notifications" IS 'Stores notifications for individual users.';



COMMENT ON COLUMN "public"."notifications"."recipient_uid" IS 'Foreign key to the user who receives the notification.';



COMMENT ON COLUMN "public"."notifications"."link_to" IS 'An optional slug (like "members") for client-side navigation.';



COMMENT ON COLUMN "public"."notifications"."user_uid" IS 'user uid';



ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."playground_project_activity" (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "action" "text" NOT NULL,
    "detail" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."playground_project_activity" OWNER TO "postgres";


ALTER TABLE "public"."playground_project_activity" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."playground_project_activity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."playground_project_files" (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "path" "text" NOT NULL,
    "created_by" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."playground_project_files" OWNER TO "postgres";


ALTER TABLE "public"."playground_project_files" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."playground_project_files_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."playground_project_members" (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "added_by" "text" NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."playground_project_members" OWNER TO "postgres";


ALTER TABLE "public"."playground_project_members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."playground_project_members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."playground_projects" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "language" "text" NOT NULL,
    "created_by" "text" NOT NULL,
    "team_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."playground_projects" OWNER TO "postgres";


ALTER TABLE "public"."playground_projects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."playground_projects_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."poll_options" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "feed_item_id" bigint,
    "text" "text" NOT NULL
);


ALTER TABLE "public"."poll_options" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."poll_votes" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "poll_option_id" "uuid",
    "user_uid" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."poll_votes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."project_columns" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "column_order" integer NOT NULL,
    "position" bigint
);


ALTER TABLE "public"."project_columns" OWNER TO "postgres";


COMMENT ON COLUMN "public"."project_columns"."position" IS 'This column is used to determine the order in which the columns (like ''Backlog'', ''In Progress'', ''Done'') are displayed on the Projects Board. The columns are sorted in ascending order';



CREATE SEQUENCE IF NOT EXISTS "public"."project_columns_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."project_columns_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."project_columns_id_seq" OWNED BY "public"."project_columns"."id";



CREATE TABLE IF NOT EXISTS "public"."project_task_assignees" (
    "task_id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "grade" smallint,
    "submission_file_path" "text",
    "submitted_at" timestamp with time zone,
    "feedback" "text",
    CONSTRAINT "project_task_assignees_grade_check" CHECK ((("grade" >= 1) AND ("grade" <= 5)))
);


ALTER TABLE "public"."project_task_assignees" OWNER TO "postgres";


COMMENT ON TABLE "public"."project_task_assignees" IS 'Join table for many-to-many relationship between tasks and users.';



CREATE TABLE IF NOT EXISTS "public"."project_tasks" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "column_id" bigint NOT NULL,
    "assignee_uid" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "is_completed" boolean DEFAULT false,
    "priority" "text" DEFAULT 'MEDIUM'::"text",
    "due_date" timestamp with time zone,
    "tags" "text"[] DEFAULT '{}'::"text"[],
    "submission_file_path" "text",
    "submitted_at" timestamp with time zone
);


ALTER TABLE "public"."project_tasks" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."project_tasks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."project_tasks_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."project_tasks_id_seq" OWNED BY "public"."project_tasks"."id";



CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "endpoint" "text" NOT NULL,
    "p256dh" "text" NOT NULL,
    "auth" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."push_subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."push_subscriptions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."push_subscriptions_id_seq" OWNED BY "public"."push_subscriptions"."id";



CREATE TABLE IF NOT EXISTS "public"."resources" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "title" "text" NOT NULL,
    "description" "text",
    "type" "text" NOT NULL,
    "topic" "text",
    "url" "text",
    "file_path" "text",
    "uploader_uid" "uuid" NOT NULL,
    "category" "text"
);


ALTER TABLE "public"."resources" OWNER TO "postgres";


COMMENT ON COLUMN "public"."resources"."category" IS 'categories of resources';



CREATE TABLE IF NOT EXISTS "public"."roadmaps" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "skill_level" "text" NOT NULL,
    "topic" "text" NOT NULL,
    "content" "jsonb" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."roadmaps" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."room_members" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "room_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "role" "text" DEFAULT 'member'::"text" NOT NULL,
    "joined_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."room_members" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."rooms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text",
    "metadata" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "created_by" "uuid" DEFAULT '00000000-0000-0000-0000-000000000000'::"uuid" NOT NULL
);


ALTER TABLE "public"."rooms" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."showcase_comments" (
    "id" bigint NOT NULL,
    "showcase_item_id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."showcase_comments" OWNER TO "postgres";


ALTER TABLE "public"."showcase_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."showcase_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."showcase_items" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_uid" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "code_content" "text" NOT NULL,
    "likes" "text"[] DEFAULT '{}'::"text"[]
);


ALTER TABLE "public"."showcase_items" OWNER TO "postgres";


ALTER TABLE "public"."showcase_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."showcase_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."suggestions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "type" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "user_uid" "text" NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text" NOT NULL,
    "upvotes" "text"[] DEFAULT '{}'::"text"[],
    CONSTRAINT "suggestions_status_check" CHECK (("status" = ANY (ARRAY['PENDING'::"text", 'IN_PROGRESS'::"text", 'COMPLETED'::"text", 'REJECTED'::"text"]))),
    CONSTRAINT "suggestions_type_check" CHECK (("type" = ANY (ARRAY['FEATURE'::"text", 'BUG'::"text"])))
);


ALTER TABLE "public"."suggestions" OWNER TO "postgres";


ALTER TABLE "public"."suggestions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."suggestions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team_challenge_submissions" (
    "id" bigint NOT NULL,
    "challenge_id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "note" "text" NOT NULL,
    "submitted_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."team_challenge_submissions" OWNER TO "postgres";


ALTER TABLE "public"."team_challenge_submissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_challenge_submissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team_challenges" (
    "id" bigint NOT NULL,
    "team_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "due_date" "date",
    "created_by" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."team_challenges" OWNER TO "postgres";


ALTER TABLE "public"."team_challenges" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_challenges_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team_join_requests" (
    "id" bigint NOT NULL,
    "team_id" bigint NOT NULL,
    "requester_uid" "text" NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "reviewed_by" "text",
    "reviewed_at" timestamp with time zone
);


ALTER TABLE "public"."team_join_requests" OWNER TO "postgres";


ALTER TABLE "public"."team_join_requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_join_requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team_members" (
    "id" bigint NOT NULL,
    "team_id" bigint NOT NULL,
    "user_uid" "text" NOT NULL,
    "joined_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."team_members" OWNER TO "postgres";


ALTER TABLE "public"."team_members" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_members_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."teams" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "created_by" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."teams" OWNER TO "postgres";


ALTER TABLE "public"."teams" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_roadmap_progress" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "text" NOT NULL,
    "roadmap_id" "uuid" NOT NULL,
    "completed_milestone_indices" integer[] DEFAULT '{}'::integer[],
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."user_roadmap_progress" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_scripts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_uid" "text" NOT NULL,
    "name" "text" NOT NULL,
    "code" "text" NOT NULL
);


ALTER TABLE "public"."user_scripts" OWNER TO "postgres";


ALTER TABLE "public"."user_scripts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_scripts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_uploads" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "bucket_id" "text" NOT NULL,
    "object_name" "text" NOT NULL,
    "owner_id" "uuid" NOT NULL,
    "metadata" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."user_uploads" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."users" (
    "uid" "text" NOT NULL,
    "name" "text" NOT NULL,
    "username" "text" NOT NULL,
    "email" "text" NOT NULL,
    "role" "text" DEFAULT 'MEMBER'::"text" NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "phone_number" "text",
    "avatar_url" "text" DEFAULT ''::"text",
    "badges" "text"[] DEFAULT '{}'::"text"[],
    "last_login" timestamp with time zone,
    "skill_level" "text" DEFAULT 'BEGINNER'::"text",
    "bio" "text",
    "class_name" "text",
    "streak_count" integer DEFAULT 0 NOT NULL,
    "streak_last_active_date" "date",
    "streak_grace_used" boolean DEFAULT false NOT NULL,
    CONSTRAINT "users_role_check" CHECK (("role" = ANY (ARRAY['MEMBER'::"text", 'PATRON'::"text"]))),
    CONSTRAINT "users_status_check" CHECK (("status" = ANY (ARRAY['APPROVED'::"text", 'PENDING'::"text"])))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON COLUMN "public"."users"."phone_number" IS 'member contacts';



COMMENT ON COLUMN "public"."users"."avatar_url" IS 'storing avatar urls';



CREATE TABLE IF NOT EXISTS "public"."voting_contestants" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "position_id" "uuid",
    "user_uid" "text" NOT NULL,
    "manifesto" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'PENDING'::"text" NOT NULL,
    CONSTRAINT "voting_contestants_status_check" CHECK (("status" = ANY (ARRAY['PENDING'::"text", 'APPROVED'::"text", 'REJECTED'::"text"])))
);


ALTER TABLE "public"."voting_contestants" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."voting_positions" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "criteria" "text",
    "status" "text" DEFAULT 'OPEN'::"text",
    "due_date" timestamp with time zone NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "start_date" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "voting_positions_status_check" CHECK (("status" = ANY (ARRAY['OPEN'::"text", 'CLOSED'::"text"])))
);


ALTER TABLE "public"."voting_positions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."voting_votes" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "position_id" "uuid",
    "contestant_id" "uuid",
    "voter_uid" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."voting_votes" OWNER TO "postgres";


ALTER TABLE ONLY "public"."activities" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."activities_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."attendance" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."attendance_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."feed_items" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."feed_items_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."game_leaderboard" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."game_leaderboard_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."project_columns" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."project_columns_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."project_tasks" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."project_tasks_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."push_subscriptions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."push_subscriptions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."activities"
    ADD CONSTRAINT "activities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."activity_rsvps"
    ADD CONSTRAINT "activity_rsvps_activity_id_user_uid_key" UNIQUE ("activity_id", "user_uid");



ALTER TABLE ONLY "public"."activity_rsvps"
    ADD CONSTRAINT "activity_rsvps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_user_uid_activity_id_key" UNIQUE ("user_uid", "activity_id");



ALTER TABLE ONLY "public"."challenge_submissions"
    ADD CONSTRAINT "challenge_submissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "challenges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feature_flags"
    ADD CONSTRAINT "feature_flags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feed_comments"
    ADD CONSTRAINT "feed_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feed_items"
    ADD CONSTRAINT "feed_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_leaderboard"
    ADD CONSTRAINT "game_leaderboard_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_leaderboard"
    ADD CONSTRAINT "game_leaderboard_user_uid_game_key_key" UNIQUE ("user_uid", "game_key");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_user_uid_key" UNIQUE ("user_uid");



ALTER TABLE ONLY "public"."playground_project_activity"
    ADD CONSTRAINT "playground_project_activity_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."playground_project_files"
    ADD CONSTRAINT "playground_project_files_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."playground_project_files"
    ADD CONSTRAINT "playground_project_files_project_id_path_key" UNIQUE ("project_id", "path");



ALTER TABLE ONLY "public"."playground_project_members"
    ADD CONSTRAINT "playground_project_members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."playground_project_members"
    ADD CONSTRAINT "playground_project_members_project_id_user_uid_key" UNIQUE ("project_id", "user_uid");



ALTER TABLE ONLY "public"."playground_projects"
    ADD CONSTRAINT "playground_projects_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."poll_options"
    ADD CONSTRAINT "poll_options_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."poll_votes"
    ADD CONSTRAINT "poll_votes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."poll_votes"
    ADD CONSTRAINT "poll_votes_poll_option_id_user_uid_key" UNIQUE ("poll_option_id", "user_uid");



ALTER TABLE ONLY "public"."project_columns"
    ADD CONSTRAINT "project_columns_column_order_key" UNIQUE ("column_order");



ALTER TABLE ONLY "public"."project_columns"
    ADD CONSTRAINT "project_columns_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."project_task_assignees"
    ADD CONSTRAINT "project_task_assignees_pkey" PRIMARY KEY ("task_id", "user_uid");



ALTER TABLE ONLY "public"."project_tasks"
    ADD CONSTRAINT "project_tasks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE ("endpoint");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."resources"
    ADD CONSTRAINT "resources_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roadmaps"
    ADD CONSTRAINT "roadmaps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."room_members"
    ADD CONSTRAINT "room_members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."room_members"
    ADD CONSTRAINT "room_members_room_id_user_id_key" UNIQUE ("room_id", "user_id");



ALTER TABLE ONLY "public"."rooms"
    ADD CONSTRAINT "rooms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."showcase_comments"
    ADD CONSTRAINT "showcase_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."showcase_items"
    ADD CONSTRAINT "showcase_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."suggestions"
    ADD CONSTRAINT "suggestions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team_challenge_submissions"
    ADD CONSTRAINT "team_challenge_submissions_challenge_id_user_uid_key" UNIQUE ("challenge_id", "user_uid");



ALTER TABLE ONLY "public"."team_challenge_submissions"
    ADD CONSTRAINT "team_challenge_submissions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team_challenges"
    ADD CONSTRAINT "team_challenges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team_join_requests"
    ADD CONSTRAINT "team_join_requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team_members"
    ADD CONSTRAINT "team_members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team_members"
    ADD CONSTRAINT "team_members_team_id_user_uid_key" UNIQUE ("team_id", "user_uid");



ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roadmap_progress"
    ADD CONSTRAINT "user_roadmap_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_roadmap_progress"
    ADD CONSTRAINT "user_roadmap_progress_user_id_roadmap_id_key" UNIQUE ("user_id", "roadmap_id");



ALTER TABLE ONLY "public"."user_scripts"
    ADD CONSTRAINT "user_scripts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_scripts"
    ADD CONSTRAINT "user_scripts_user_uid_name_key" UNIQUE ("user_uid", "name");



ALTER TABLE ONLY "public"."user_uploads"
    ADD CONSTRAINT "user_uploads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."voting_contestants"
    ADD CONSTRAINT "voting_contestants_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."voting_contestants"
    ADD CONSTRAINT "voting_contestants_position_id_user_uid_key" UNIQUE ("position_id", "user_uid");



ALTER TABLE ONLY "public"."voting_positions"
    ADD CONSTRAINT "voting_positions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."voting_votes"
    ADD CONSTRAINT "voting_votes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."voting_votes"
    ADD CONSTRAINT "voting_votes_position_id_voter_uid_key" UNIQUE ("position_id", "voter_uid");



CREATE INDEX "idx_game_leaderboard_game_key" ON "public"."game_leaderboard" USING "btree" ("game_key");



CREATE INDEX "idx_messages_room_created_at" ON "public"."messages" USING "btree" ("room_id", "created_at" DESC);



CREATE INDEX "idx_messages_sender_id" ON "public"."messages" USING "btree" ("sender_id");



CREATE UNIQUE INDEX "idx_notifications_dedupe" ON "public"."notifications" USING "btree" ("user_uid", "message", "link_to");



CREATE INDEX "idx_playground_project_activity_project_id" ON "public"."playground_project_activity" USING "btree" ("project_id");



CREATE INDEX "idx_playground_project_files_project_id" ON "public"."playground_project_files" USING "btree" ("project_id");



CREATE INDEX "idx_playground_project_members_project_id" ON "public"."playground_project_members" USING "btree" ("project_id");



CREATE INDEX "idx_playground_project_members_user_uid" ON "public"."playground_project_members" USING "btree" ("user_uid");



CREATE INDEX "idx_playground_projects_team_id" ON "public"."playground_projects" USING "btree" ("team_id");



CREATE INDEX "idx_push_subscriptions_user_uid" ON "public"."push_subscriptions" USING "btree" ("user_uid");



CREATE INDEX "idx_room_members_room_user" ON "public"."room_members" USING "btree" ("room_id", "user_id");



CREATE INDEX "idx_team_challenge_submissions_challenge_id" ON "public"."team_challenge_submissions" USING "btree" ("challenge_id");



CREATE INDEX "idx_team_challenge_submissions_user_uid" ON "public"."team_challenge_submissions" USING "btree" ("user_uid");



CREATE INDEX "idx_team_challenges_team_id" ON "public"."team_challenges" USING "btree" ("team_id");



CREATE UNIQUE INDEX "idx_team_join_requests_unique" ON "public"."team_join_requests" USING "btree" ("team_id", "requester_uid");



CREATE INDEX "idx_team_members_team_id" ON "public"."team_members" USING "btree" ("team_id");



CREATE INDEX "idx_team_members_user_uid" ON "public"."team_members" USING "btree" ("user_uid");



CREATE INDEX "idx_user_uploads_owner_id" ON "public"."user_uploads" USING "btree" ("owner_id");



CREATE OR REPLACE TRIGGER "messages_broadcast_trigger" AFTER INSERT OR DELETE OR UPDATE ON "public"."messages" FOR EACH ROW EXECUTE FUNCTION "public"."room_messages_broadcast_trigger"();



CREATE OR REPLACE TRIGGER "public_messages_broadcast_trigger" AFTER INSERT OR DELETE OR UPDATE ON "public"."messages" FOR EACH ROW EXECUTE FUNCTION "public"."broadcast_public_messages_trigger"();



CREATE OR REPLACE TRIGGER "user_uploads_set_updated_at" BEFORE UPDATE ON "public"."user_uploads" FOR EACH ROW EXECUTE FUNCTION "public"."user_uploads_updated_at"();



ALTER TABLE ONLY "public"."activity_rsvps"
    ADD CONSTRAINT "activity_rsvps_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."activity_rsvps"
    ADD CONSTRAINT "activity_rsvps_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "public"."activities"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."challenge_submissions"
    ADD CONSTRAINT "challenge_submissions_challenge_id_fkey" FOREIGN KEY ("challenge_id") REFERENCES "public"."challenges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."challenge_submissions"
    ADD CONSTRAINT "challenge_submissions_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "challenges_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("uid");



ALTER TABLE ONLY "public"."feed_comments"
    ADD CONSTRAINT "feed_comments_feed_item_id_fkey" FOREIGN KEY ("feed_item_id") REFERENCES "public"."feed_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."feed_comments"
    ADD CONSTRAINT "feed_comments_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."feed_items"
    ADD CONSTRAINT "feed_items_author_uid_fkey" FOREIGN KEY ("author_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_leaderboard"
    ADD CONSTRAINT "game_leaderboard_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_activity"
    ADD CONSTRAINT "playground_project_activity_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."playground_projects"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_activity"
    ADD CONSTRAINT "playground_project_activity_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_files"
    ADD CONSTRAINT "playground_project_files_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_files"
    ADD CONSTRAINT "playground_project_files_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."playground_projects"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_members"
    ADD CONSTRAINT "playground_project_members_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_members"
    ADD CONSTRAINT "playground_project_members_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."playground_projects"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_project_members"
    ADD CONSTRAINT "playground_project_members_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_projects"
    ADD CONSTRAINT "playground_projects_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."playground_projects"
    ADD CONSTRAINT "playground_projects_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."poll_options"
    ADD CONSTRAINT "poll_options_feed_item_id_fkey" FOREIGN KEY ("feed_item_id") REFERENCES "public"."feed_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."poll_votes"
    ADD CONSTRAINT "poll_votes_poll_option_id_fkey" FOREIGN KEY ("poll_option_id") REFERENCES "public"."poll_options"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."poll_votes"
    ADD CONSTRAINT "poll_votes_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_task_assignees"
    ADD CONSTRAINT "project_task_assignees_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "public"."project_tasks"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_task_assignees"
    ADD CONSTRAINT "project_task_assignees_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_tasks"
    ADD CONSTRAINT "project_tasks_assignee_uid_fkey" FOREIGN KEY ("assignee_uid") REFERENCES "public"."users"("uid") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."project_tasks"
    ADD CONSTRAINT "project_tasks_column_id_fkey" FOREIGN KEY ("column_id") REFERENCES "public"."project_columns"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."room_members"
    ADD CONSTRAINT "room_members_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."showcase_comments"
    ADD CONSTRAINT "showcase_comments_item_id_fkey" FOREIGN KEY ("showcase_item_id") REFERENCES "public"."showcase_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."showcase_comments"
    ADD CONSTRAINT "showcase_comments_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."showcase_items"
    ADD CONSTRAINT "showcase_items_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."suggestions"
    ADD CONSTRAINT "suggestions_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid");



ALTER TABLE ONLY "public"."team_challenge_submissions"
    ADD CONSTRAINT "team_challenge_submissions_challenge_id_fkey" FOREIGN KEY ("challenge_id") REFERENCES "public"."team_challenges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_challenge_submissions"
    ADD CONSTRAINT "team_challenge_submissions_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_challenges"
    ADD CONSTRAINT "team_challenges_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_challenges"
    ADD CONSTRAINT "team_challenges_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_join_requests"
    ADD CONSTRAINT "team_join_requests_requester_uid_fkey" FOREIGN KEY ("requester_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_join_requests"
    ADD CONSTRAINT "team_join_requests_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("uid") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."team_join_requests"
    ADD CONSTRAINT "team_join_requests_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_members"
    ADD CONSTRAINT "team_members_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."team_members"
    ADD CONSTRAINT "team_members_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."teams"
    ADD CONSTRAINT "teams_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_roadmap_progress"
    ADD CONSTRAINT "user_roadmap_progress_roadmap_id_fkey" FOREIGN KEY ("roadmap_id") REFERENCES "public"."roadmaps"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_roadmap_progress"
    ADD CONSTRAINT "user_roadmap_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("uid");



ALTER TABLE ONLY "public"."user_scripts"
    ADD CONSTRAINT "user_scripts_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid");



ALTER TABLE ONLY "public"."voting_contestants"
    ADD CONSTRAINT "voting_contestants_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "public"."voting_positions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voting_contestants"
    ADD CONSTRAINT "voting_contestants_user_uid_fkey" FOREIGN KEY ("user_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voting_positions"
    ADD CONSTRAINT "voting_positions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."voting_votes"
    ADD CONSTRAINT "voting_votes_contestant_id_fkey" FOREIGN KEY ("contestant_id") REFERENCES "public"."voting_contestants"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voting_votes"
    ADD CONSTRAINT "voting_votes_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "public"."voting_positions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."voting_votes"
    ADD CONSTRAINT "voting_votes_voter_uid_fkey" FOREIGN KEY ("voter_uid") REFERENCES "public"."users"("uid") ON DELETE CASCADE;



CREATE POLICY "Activities are viewable by authenticated users." ON "public"."activities" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Anyone can view contestants" ON "public"."voting_contestants" FOR SELECT USING (true);



CREATE POLICY "Anyone can view positions" ON "public"."voting_positions" FOR SELECT USING (true);



CREATE POLICY "Authenticated users can vote" ON "public"."voting_votes" FOR INSERT WITH CHECK (((("auth"."uid"())::"text" = "voter_uid") AND (EXISTS ( SELECT 1
   FROM "public"."voting_positions"
  WHERE (("voting_positions"."id" = "voting_votes"."position_id") AND ("now"() >= "voting_positions"."start_date") AND ("now"() <= "voting_positions"."due_date"))))));



CREATE POLICY "Challenges are viewable by everyone" ON "public"."challenges" FOR SELECT USING (true);



CREATE POLICY "Contestants insert patron only" ON "public"."voting_contestants" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."users" "u"
  WHERE (("u"."uid" = ("auth"."uid"())::"text") AND ("u"."role" = 'PATRON'::"text")))));



CREATE POLICY "Enable delete for owners" ON "public"."resources" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "uploader_uid"));



CREATE POLICY "Enable insert for authenticated users" ON "public"."resources" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "uploader_uid"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."activity_rsvps" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."messages" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."messages" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."resources" FOR SELECT USING (true);



CREATE POLICY "Feature flags select" ON "public"."feature_flags" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Feature flags update" ON "public"."feature_flags" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."users" "u"
  WHERE (("u"."uid" = ("auth"."uid"())::"text") AND ("u"."role" = 'PATRON'::"text")))));



CREATE POLICY "Feed items are viewable by authenticated users." ON "public"."feed_items" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Leaderboard select" ON "public"."game_leaderboard" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Leaderboard update own" ON "public"."game_leaderboard" FOR UPDATE USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Leaderboard upsert own" ON "public"."game_leaderboard" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Members can contest" ON "public"."voting_contestants" FOR INSERT WITH CHECK (((("auth"."uid"())::"text" = "user_uid") AND (EXISTS ( SELECT 1
   FROM "public"."voting_positions"
  WHERE (("voting_positions"."id" = "voting_contestants"."position_id") AND ("now"() >= "voting_positions"."start_date") AND ("now"() <= "voting_positions"."due_date"))))));



CREATE POLICY "Members can leave or owner can remove" ON "public"."team_members" FOR DELETE USING (((("auth"."uid"())::"text" = "user_uid") OR (EXISTS ( SELECT 1
   FROM "public"."teams" "t"
  WHERE (("t"."id" = "team_members"."team_id") AND ("t"."created_by" = ("auth"."uid"())::"text"))))));



CREATE POLICY "Members can submit solutions" ON "public"."challenge_submissions" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Members change vote" ON "public"."poll_votes" FOR DELETE TO "authenticated" USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Members update vote" ON "public"."poll_votes" FOR UPDATE TO "authenticated" USING ((("auth"."uid"())::"text" = "user_uid")) WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Members vote" ON "public"."poll_votes" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Patrons can create positions" ON "public"."voting_positions" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."uid" = ("auth"."uid"())::"text") AND ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Patrons can delete positions" ON "public"."voting_positions" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."uid" = ("auth"."uid"())::"text") AND ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Patrons can insert challenges" ON "public"."challenges" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" IN ( SELECT "users"."uid"
   FROM "public"."users"
  WHERE ("users"."role" = 'PATRON'::"text"))));



CREATE POLICY "Patrons can manage activities." ON "public"."activities" USING ((( SELECT "users"."role"
   FROM "public"."users"
  WHERE ("users"."uid" = ("auth"."uid"())::"text")) = 'PATRON'::"text"));



CREATE POLICY "Patrons can manage project board." ON "public"."project_columns" USING ((( SELECT "users"."role"
   FROM "public"."users"
  WHERE ("users"."uid" = ("auth"."uid"())::"text")) = 'PATRON'::"text"));



CREATE POLICY "Patrons can manage project tasks." ON "public"."project_tasks" USING ((( SELECT "users"."role"
   FROM "public"."users"
  WHERE ("users"."uid" = ("auth"."uid"())::"text")) = 'PATRON'::"text"));



CREATE POLICY "Patrons can moderate contestants" ON "public"."voting_contestants" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."uid" = ("auth"."uid"())::"text") AND ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Patrons can post feed items." ON "public"."feed_items" FOR INSERT WITH CHECK ((( SELECT "users"."role"
   FROM "public"."users"
  WHERE ("users"."uid" = ("auth"."uid"())::"text")) = 'PATRON'::"text"));



CREATE POLICY "Patrons can review submissions" ON "public"."challenge_submissions" FOR UPDATE USING ((("auth"."uid"())::"text" IN ( SELECT "users"."uid"
   FROM "public"."users"
  WHERE ("users"."role" = 'PATRON'::"text"))));



CREATE POLICY "Patrons can see all votes" ON "public"."voting_votes" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."uid" = ("auth"."uid"())::"text") AND ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Patrons can update challenges" ON "public"."challenges" FOR UPDATE USING ((("auth"."uid"())::"text" IN ( SELECT "users"."uid"
   FROM "public"."users"
  WHERE ("users"."role" = 'PATRON'::"text"))));



CREATE POLICY "Patrons can update positions" ON "public"."voting_positions" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."uid" = ("auth"."uid"())::"text") AND ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Patrons can update user profiles" ON "public"."users" FOR UPDATE USING (((("auth"."uid"())::"text" = "uid") OR (("auth"."uid"())::"text" IN ( SELECT "users_1"."uid"
   FROM "public"."users" "users_1"
  WHERE ("users_1"."role" = 'PATRON'::"text")))));



CREATE POLICY "Patrons can view all attendance records." ON "public"."attendance" FOR SELECT USING ((( SELECT "users"."role"
   FROM "public"."users"
  WHERE ("users"."uid" = ("auth"."uid"())::"text")) = 'PATRON'::"text"));



CREATE POLICY "Patrons create poll options" ON "public"."poll_options" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."users"
  WHERE (("users"."uid" = ("auth"."uid"())::"text") AND ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Playground activity insert" ON "public"."playground_project_activity" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_activity"."project_id") AND (("p"."created_by" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
           FROM "public"."playground_project_members" "ppm"
          WHERE (("ppm"."project_id" = "p"."id") AND ("ppm"."user_uid" = ("auth"."uid"())::"text")))) OR (("p"."team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
           FROM "public"."team_members" "tm"
          WHERE (("tm"."team_id" = "p"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text"))))))))));



CREATE POLICY "Playground activity select" ON "public"."playground_project_activity" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Playground files delete" ON "public"."playground_project_files" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_files"."project_id") AND (("p"."created_by" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
           FROM "public"."playground_project_members" "ppm"
          WHERE (("ppm"."project_id" = "p"."id") AND ("ppm"."user_uid" = ("auth"."uid"())::"text")))) OR (("p"."team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
           FROM "public"."team_members" "tm"
          WHERE (("tm"."team_id" = "p"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text"))))))))));



CREATE POLICY "Playground files insert" ON "public"."playground_project_files" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_files"."project_id") AND (("p"."created_by" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
           FROM "public"."playground_project_members" "ppm"
          WHERE (("ppm"."project_id" = "p"."id") AND ("ppm"."user_uid" = ("auth"."uid"())::"text")))) OR (("p"."team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
           FROM "public"."team_members" "tm"
          WHERE (("tm"."team_id" = "p"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text"))))))))));



CREATE POLICY "Playground files select" ON "public"."playground_project_files" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Playground files update" ON "public"."playground_project_files" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_files"."project_id") AND (("p"."created_by" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
           FROM "public"."playground_project_members" "ppm"
          WHERE (("ppm"."project_id" = "p"."id") AND ("ppm"."user_uid" = ("auth"."uid"())::"text")))) OR (("p"."team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
           FROM "public"."team_members" "tm"
          WHERE (("tm"."team_id" = "p"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text")))))))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_files"."project_id") AND (("p"."created_by" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
           FROM "public"."playground_project_members" "ppm"
          WHERE (("ppm"."project_id" = "p"."id") AND ("ppm"."user_uid" = ("auth"."uid"())::"text")))) OR (("p"."team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
           FROM "public"."team_members" "tm"
          WHERE (("tm"."team_id" = "p"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text"))))))))));



CREATE POLICY "Playground projects create" ON "public"."playground_projects" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Playground projects delete" ON "public"."playground_projects" FOR DELETE USING (((("auth"."uid"())::"text" = "created_by") OR (("team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM "public"."team_members" "tm"
  WHERE (("tm"."team_id" = "playground_projects"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text")))))));



CREATE POLICY "Playground projects update" ON "public"."playground_projects" FOR UPDATE USING (((("auth"."uid"())::"text" = "created_by") OR (("team_id" IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM "public"."team_members" "tm"
  WHERE (("tm"."team_id" = "playground_projects"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text")))))));



CREATE POLICY "Playground projects visible to authenticated users" ON "public"."playground_projects" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Project board is viewable by authenticated users." ON "public"."project_columns" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Project members delete" ON "public"."playground_project_members" FOR DELETE USING ((("user_uid" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_members"."project_id") AND ("p"."created_by" = ("auth"."uid"())::"text"))))));



CREATE POLICY "Project members insert" ON "public"."playground_project_members" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."playground_projects" "p"
  WHERE (("p"."id" = "playground_project_members"."project_id") AND (("p"."created_by" = ("auth"."uid"())::"text") OR (EXISTS ( SELECT 1
           FROM "public"."team_members" "tm"
          WHERE (("tm"."team_id" = "p"."team_id") AND ("tm"."user_uid" = ("auth"."uid"())::"text")))) OR (EXISTS ( SELECT 1
           FROM "public"."playground_project_members" "ppm"
          WHERE (("ppm"."project_id" = "p"."id") AND ("ppm"."user_uid" = ("auth"."uid"())::"text")))))))));



CREATE POLICY "Project members visible" ON "public"."playground_project_members" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Project tasks are viewable by authenticated users." ON "public"."project_tasks" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Public comments are viewable by everyone." ON "public"."feed_comments" FOR SELECT USING (true);



CREATE POLICY "Public read poll options" ON "public"."poll_options" FOR SELECT USING (true);



CREATE POLICY "Public read votes" ON "public"."poll_votes" FOR SELECT USING (true);



CREATE POLICY "Public view suggestions" ON "public"."suggestions" FOR SELECT USING (true);



CREATE POLICY "Push subs delete own" ON "public"."push_subscriptions" FOR DELETE USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Push subs insert own" ON "public"."push_subscriptions" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Push subs select own" ON "public"."push_subscriptions" FOR SELECT USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Showcase items are viewable by everyone." ON "public"."showcase_items" FOR SELECT USING (true);



CREATE POLICY "Team challenge creator can create" ON "public"."team_challenges" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Team challenge creator can delete" ON "public"."team_challenges" FOR DELETE USING ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Team challenge creator can update" ON "public"."team_challenges" FOR UPDATE USING ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Team challenges visible to authenticated users" ON "public"."team_challenges" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Team creator can create team" ON "public"."teams" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Team creator can delete team" ON "public"."teams" FOR DELETE USING ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Team creator can update team" ON "public"."teams" FOR UPDATE USING ((("auth"."uid"())::"text" = "created_by"));



CREATE POLICY "Team members can be viewed by authenticated users" ON "public"."team_members" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Team owner can add members" ON "public"."team_members" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."teams" "t"
  WHERE (("t"."id" = "team_members"."team_id") AND ("t"."created_by" = ("auth"."uid"())::"text")))));



CREATE POLICY "Team submissions visible to authenticated users" ON "public"."team_challenge_submissions" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Teams can be viewed by authenticated users" ON "public"."teams" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "User delete own suggestions" ON "public"."suggestions" FOR DELETE USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "User insert suggestions" ON "public"."suggestions" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "User manage own scripts" ON "public"."user_scripts" USING ((("auth"."uid"())::"text" = "user_uid")) WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "User update suggestions" ON "public"."suggestions" FOR UPDATE USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Users are viewable by authenticated users." ON "public"."users" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can delete their own comments." ON "public"."feed_comments" FOR DELETE USING (("auth"."uid"() = "user_uid"));



CREATE POLICY "Users can delete their own showcase items." ON "public"."showcase_items" FOR DELETE USING (("auth"."uid"() = "user_uid"));



CREATE POLICY "Users can delete their submission" ON "public"."team_challenge_submissions" FOR DELETE USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Users can insert their own comments." ON "public"."feed_comments" FOR INSERT WITH CHECK (("auth"."uid"() = "user_uid"));



CREATE POLICY "Users can insert their own profile." ON "public"."users" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "uid"));



CREATE POLICY "Users can insert their own showcase items." ON "public"."showcase_items" FOR INSERT WITH CHECK (("auth"."uid"() = "user_uid"));



CREATE POLICY "Users can join themselves" ON "public"."team_members" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Users can leave themselves" ON "public"."team_members" FOR DELETE USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Users can submit for themselves" ON "public"."team_challenge_submissions" FOR INSERT WITH CHECK ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Users can update showcase items." ON "public"."showcase_items" FOR UPDATE USING (true);



CREATE POLICY "Users can update their own notifications" ON "public"."notifications" FOR UPDATE USING (("auth"."uid"() = "recipient_uid")) WITH CHECK (("auth"."uid"() = "recipient_uid"));



CREATE POLICY "Users can update their own profile." ON "public"."users" FOR UPDATE USING ((("auth"."uid"())::"text" = "uid"));



CREATE POLICY "Users can update their submission" ON "public"."team_challenge_submissions" FOR UPDATE USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Users can view and manage their own attendance." ON "public"."attendance" USING ((("auth"."uid"())::"text" = "user_uid"));



CREATE POLICY "Users can view their own notifications" ON "public"."notifications" FOR SELECT USING (("auth"."uid"() = "recipient_uid"));



CREATE POLICY "Users see own submissions, Patrons see all" ON "public"."challenge_submissions" FOR SELECT USING (((("auth"."uid"())::"text" = "user_uid") OR (("auth"."uid"())::"text" IN ( SELECT "users"."uid"
   FROM "public"."users"
  WHERE ("users"."role" = 'PATRON'::"text")))));



CREATE POLICY "Voters can see their own votes" ON "public"."voting_votes" FOR SELECT USING ((("auth"."uid"())::"text" = "voter_uid"));



ALTER TABLE "public"."activities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."challenge_submissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."challenges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feature_flags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feed_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feed_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_leaderboard" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "messages_delete_sender_or_moderator" ON "public"."messages" FOR DELETE TO "authenticated" USING ((("sender_id" = "public"."current_user_id"()) OR (EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "messages"."room_id") AND ("rm"."user_id" = "public"."current_user_id"()) AND ("rm"."role" = 'moderator'::"text"))))));



CREATE POLICY "messages_insert_sender_is_member" ON "public"."messages" FOR INSERT TO "authenticated" WITH CHECK ((("sender_id" = "public"."current_user_id"()) AND (EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "messages"."room_id") AND ("rm"."user_id" = "public"."current_user_id"()))))));



CREATE POLICY "messages_select_room_members" ON "public"."messages" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "messages"."room_id") AND ("rm"."user_id" = "public"."current_user_id"())))));



CREATE POLICY "messages_update_sender_or_moderator" ON "public"."messages" FOR UPDATE TO "authenticated" USING ((("sender_id" = "public"."current_user_id"()) OR (EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "messages"."room_id") AND ("rm"."user_id" = "public"."current_user_id"()) AND ("rm"."role" = 'moderator'::"text")))))) WITH CHECK ((("sender_id" = "public"."current_user_id"()) OR (EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "messages"."room_id") AND ("rm"."user_id" = "public"."current_user_id"()) AND ("rm"."role" = 'moderator'::"text"))))));



ALTER TABLE "public"."playground_project_activity" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."playground_project_files" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."playground_project_members" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."playground_projects" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."poll_options" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."poll_votes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."resources" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "room_members_delete_owner_only" ON "public"."room_members" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."room_members" "owner_rm"
  WHERE (("owner_rm"."room_id" = "room_members"."room_id") AND ("owner_rm"."user_id" = "public"."current_user_id"()) AND ("owner_rm"."role" = 'owner'::"text")))));



CREATE POLICY "room_members_insert_self" ON "public"."room_members" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "public"."current_user_id"()));



CREATE POLICY "room_members_select_self" ON "public"."room_members" FOR SELECT TO "authenticated" USING (("user_id" = "public"."current_user_id"()));



CREATE POLICY "room_members_update_owner_only" ON "public"."room_members" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."room_members" "owner_rm"
  WHERE (("owner_rm"."room_id" = "room_members"."room_id") AND ("owner_rm"."user_id" = "public"."current_user_id"()) AND ("owner_rm"."role" = 'owner'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."room_members" "owner_rm"
  WHERE (("owner_rm"."room_id" = "room_members"."room_id") AND ("owner_rm"."user_id" = "public"."current_user_id"()) AND ("owner_rm"."role" = 'owner'::"text")))));



CREATE POLICY "rooms_insert_authenticated" ON "public"."rooms" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "rooms_select_for_members" ON "public"."rooms" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "rooms"."id") AND ("rm"."user_id" = "public"."current_user_id"())))));



CREATE POLICY "rooms_update_owner_or_moderator" ON "public"."rooms" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "rooms"."id") AND ("rm"."user_id" = "public"."current_user_id"()) AND ("rm"."role" = ANY (ARRAY['owner'::"text", 'moderator'::"text"])))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."room_members" "rm"
  WHERE (("rm"."room_id" = "rooms"."id") AND ("rm"."user_id" = "public"."current_user_id"()) AND ("rm"."role" = ANY (ARRAY['owner'::"text", 'moderator'::"text"]))))));



ALTER TABLE "public"."showcase_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."suggestions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."team_challenge_submissions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."team_challenges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."team_members" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."teams" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_scripts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "users_delete_own_uploads" ON "public"."user_uploads" FOR DELETE TO "authenticated" USING (("owner_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "users_insert_own_uploads" ON "public"."user_uploads" FOR INSERT TO "authenticated" WITH CHECK ((("owner_id" IS NOT NULL) AND ("owner_id" = ( SELECT "auth"."uid"() AS "uid"))));



CREATE POLICY "users_select_own_uploads" ON "public"."user_uploads" FOR SELECT TO "authenticated" USING (("owner_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "users_update_own_uploads" ON "public"."user_uploads" FOR UPDATE TO "authenticated" USING (("owner_id" = ( SELECT "auth"."uid"() AS "uid"))) WITH CHECK (("owner_id" = ( SELECT "auth"."uid"() AS "uid")));



ALTER TABLE "public"."voting_contestants" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."voting_positions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."voting_votes" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."feed_items";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."messages";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT ALL ON FUNCTION "public"."broadcast_public_messages_trigger"() TO "anon";
GRANT ALL ON FUNCTION "public"."broadcast_public_messages_trigger"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."broadcast_public_messages_trigger"() TO "service_role";



GRANT ALL ON FUNCTION "public"."current_user_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."room_messages_broadcast_trigger"() TO "anon";
GRANT ALL ON FUNCTION "public"."room_messages_broadcast_trigger"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."room_messages_broadcast_trigger"() TO "service_role";



GRANT ALL ON FUNCTION "public"."user_uploads_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."user_uploads_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."user_uploads_updated_at"() TO "service_role";
























GRANT ALL ON TABLE "public"."activities" TO "anon";
GRANT ALL ON TABLE "public"."activities" TO "authenticated";
GRANT ALL ON TABLE "public"."activities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."activity_rsvps" TO "anon";
GRANT ALL ON TABLE "public"."activity_rsvps" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_rsvps" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activity_rsvps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activity_rsvps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activity_rsvps_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."attendance" TO "anon";
GRANT ALL ON TABLE "public"."attendance" TO "authenticated";
GRANT ALL ON TABLE "public"."attendance" TO "service_role";



GRANT ALL ON SEQUENCE "public"."attendance_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."attendance_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."attendance_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."challenge_submissions" TO "anon";
GRANT ALL ON TABLE "public"."challenge_submissions" TO "authenticated";
GRANT ALL ON TABLE "public"."challenge_submissions" TO "service_role";



GRANT ALL ON TABLE "public"."challenges" TO "anon";
GRANT ALL ON TABLE "public"."challenges" TO "authenticated";
GRANT ALL ON TABLE "public"."challenges" TO "service_role";



GRANT ALL ON TABLE "public"."feature_flags" TO "anon";
GRANT ALL ON TABLE "public"."feature_flags" TO "authenticated";
GRANT ALL ON TABLE "public"."feature_flags" TO "service_role";



GRANT ALL ON TABLE "public"."feed_comments" TO "anon";
GRANT ALL ON TABLE "public"."feed_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."feed_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."feed_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feed_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feed_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."feed_items" TO "anon";
GRANT ALL ON TABLE "public"."feed_items" TO "authenticated";
GRANT ALL ON TABLE "public"."feed_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."feed_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feed_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feed_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game_leaderboard" TO "anon";
GRANT ALL ON TABLE "public"."game_leaderboard" TO "authenticated";
GRANT ALL ON TABLE "public"."game_leaderboard" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_leaderboard_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_leaderboard_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_leaderboard_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."playground_project_activity" TO "anon";
GRANT ALL ON TABLE "public"."playground_project_activity" TO "authenticated";
GRANT ALL ON TABLE "public"."playground_project_activity" TO "service_role";



GRANT ALL ON SEQUENCE "public"."playground_project_activity_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."playground_project_activity_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."playground_project_activity_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."playground_project_files" TO "anon";
GRANT ALL ON TABLE "public"."playground_project_files" TO "authenticated";
GRANT ALL ON TABLE "public"."playground_project_files" TO "service_role";



GRANT ALL ON SEQUENCE "public"."playground_project_files_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."playground_project_files_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."playground_project_files_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."playground_project_members" TO "anon";
GRANT ALL ON TABLE "public"."playground_project_members" TO "authenticated";
GRANT ALL ON TABLE "public"."playground_project_members" TO "service_role";



GRANT ALL ON SEQUENCE "public"."playground_project_members_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."playground_project_members_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."playground_project_members_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."playground_projects" TO "anon";
GRANT ALL ON TABLE "public"."playground_projects" TO "authenticated";
GRANT ALL ON TABLE "public"."playground_projects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."playground_projects_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."playground_projects_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."playground_projects_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."poll_options" TO "anon";
GRANT ALL ON TABLE "public"."poll_options" TO "authenticated";
GRANT ALL ON TABLE "public"."poll_options" TO "service_role";



GRANT ALL ON TABLE "public"."poll_votes" TO "anon";
GRANT ALL ON TABLE "public"."poll_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."poll_votes" TO "service_role";



GRANT ALL ON TABLE "public"."project_columns" TO "anon";
GRANT ALL ON TABLE "public"."project_columns" TO "authenticated";
GRANT ALL ON TABLE "public"."project_columns" TO "service_role";



GRANT ALL ON SEQUENCE "public"."project_columns_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project_columns_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project_columns_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."project_task_assignees" TO "anon";
GRANT ALL ON TABLE "public"."project_task_assignees" TO "authenticated";
GRANT ALL ON TABLE "public"."project_task_assignees" TO "service_role";



GRANT ALL ON TABLE "public"."project_tasks" TO "anon";
GRANT ALL ON TABLE "public"."project_tasks" TO "authenticated";
GRANT ALL ON TABLE "public"."project_tasks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."project_tasks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project_tasks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project_tasks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."resources" TO "anon";
GRANT ALL ON TABLE "public"."resources" TO "authenticated";
GRANT ALL ON TABLE "public"."resources" TO "service_role";



GRANT ALL ON TABLE "public"."roadmaps" TO "anon";
GRANT ALL ON TABLE "public"."roadmaps" TO "authenticated";
GRANT ALL ON TABLE "public"."roadmaps" TO "service_role";



GRANT ALL ON TABLE "public"."room_members" TO "anon";
GRANT ALL ON TABLE "public"."room_members" TO "authenticated";
GRANT ALL ON TABLE "public"."room_members" TO "service_role";



GRANT ALL ON TABLE "public"."rooms" TO "anon";
GRANT ALL ON TABLE "public"."rooms" TO "authenticated";
GRANT ALL ON TABLE "public"."rooms" TO "service_role";



GRANT ALL ON TABLE "public"."showcase_comments" TO "anon";
GRANT ALL ON TABLE "public"."showcase_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."showcase_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."showcase_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."showcase_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."showcase_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."showcase_items" TO "anon";
GRANT ALL ON TABLE "public"."showcase_items" TO "authenticated";
GRANT ALL ON TABLE "public"."showcase_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."showcase_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."showcase_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."showcase_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."suggestions" TO "anon";
GRANT ALL ON TABLE "public"."suggestions" TO "authenticated";
GRANT ALL ON TABLE "public"."suggestions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."suggestions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."suggestions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."suggestions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."team_challenge_submissions" TO "anon";
GRANT ALL ON TABLE "public"."team_challenge_submissions" TO "authenticated";
GRANT ALL ON TABLE "public"."team_challenge_submissions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."team_challenge_submissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."team_challenge_submissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."team_challenge_submissions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."team_challenges" TO "anon";
GRANT ALL ON TABLE "public"."team_challenges" TO "authenticated";
GRANT ALL ON TABLE "public"."team_challenges" TO "service_role";



GRANT ALL ON SEQUENCE "public"."team_challenges_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."team_challenges_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."team_challenges_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."team_join_requests" TO "anon";
GRANT ALL ON TABLE "public"."team_join_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."team_join_requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."team_join_requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."team_join_requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."team_join_requests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."team_members" TO "anon";
GRANT ALL ON TABLE "public"."team_members" TO "authenticated";
GRANT ALL ON TABLE "public"."team_members" TO "service_role";



GRANT ALL ON SEQUENCE "public"."team_members_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."team_members_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."team_members_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."teams" TO "anon";
GRANT ALL ON TABLE "public"."teams" TO "authenticated";
GRANT ALL ON TABLE "public"."teams" TO "service_role";



GRANT ALL ON SEQUENCE "public"."teams_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."teams_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."teams_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_roadmap_progress" TO "anon";
GRANT ALL ON TABLE "public"."user_roadmap_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."user_roadmap_progress" TO "service_role";



GRANT ALL ON TABLE "public"."user_scripts" TO "anon";
GRANT ALL ON TABLE "public"."user_scripts" TO "authenticated";
GRANT ALL ON TABLE "public"."user_scripts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_scripts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_scripts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_scripts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_uploads" TO "anon";
GRANT ALL ON TABLE "public"."user_uploads" TO "authenticated";
GRANT ALL ON TABLE "public"."user_uploads" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON TABLE "public"."voting_contestants" TO "anon";
GRANT ALL ON TABLE "public"."voting_contestants" TO "authenticated";
GRANT ALL ON TABLE "public"."voting_contestants" TO "service_role";



GRANT ALL ON TABLE "public"."voting_positions" TO "anon";
GRANT ALL ON TABLE "public"."voting_positions" TO "authenticated";
GRANT ALL ON TABLE "public"."voting_positions" TO "service_role";



GRANT ALL ON TABLE "public"."voting_votes" TO "anon";
GRANT ALL ON TABLE "public"."voting_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."voting_votes" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































